### ISSUE TITLE
tilføj Hjælpemiddelsbasen

### ISSUE THREAD

**Issue by Tvede-dk** [mauran/API-Danmark#106]
Pr
https://hmi-basen.dk/news.asp?newsid=4325&x_newstype=29
&
https://hmi-basen.dk/dataudtraek.asp

Er dataen åben, det kan være det bør tilføjes hertil også :)

**Comment by mauran** [comment]
Hej Kasper og tak for dit input 😄 

Jeg får lige tilføjet den på listen

**Comment by mauran** [comment]
Tilføjet
