### ISSUE TITLE
Tilføj dataforsyningen

### ISSUE THREAD

**Issue by Jonasmadsen** [mauran/API-Danmark#107]
Der er utrolig meget at hente her:
https://dataforsyningen.dk/data
Gratis og frit dansk data fra det offentlige.
Det er et overlap med datafordeler.dk men den har data der ikke findes i datafordeler.dk, fx Danmarks Dybdemodel (DDM)

Jeg er faktisk lidt i tvivl om hvorfor "Styrelsen for Dataforsyning og Infrastruktur" driver to så ens sider.

**Comment by mauran** [comment]
Hej Jonas, 
Jeg får den tilføjet til listen 👍🏾

**Comment by mauran** [comment]
Tilføjet
