### ISSUE TITLE
Data VS API?

### ISSUE THREAD

**Issue by mauran** [mauran/API-Danmark#111]
Hej, 
Efterhånden som tiden går, får vi flere anmodninger om tilføjelse af datasæt. Synes i at datasæt har sin plads her eller andensteds?(evt et andet repository med dansk data) 

Alle er velkommen til at komme med deres input

**Comment by LasseRafn** [comment]
God tanke! Har vi et eksempel på datasæt vs API? Bare lige for at ha’ fuld kontekst

**Comment by mauran** [comment]
Fx https://dataforsyningen.dk/data - Hvor der kan downloades data

**Comment by tykfyr** [comment]
Det burde vel være et seperat repository :)

**Comment by Tanddant** [comment]
Enig, seperat repo, medmindre man skulle re-brande repo'et til at være "Dansk data" - og så have seprate filer for fx. API'er, eller "data sider"

**Comment by LasseRafn** [comment]
Måske det giver bedst mening med separat repo, men ville være fint at eventuelt linke mellem hinanden i README ("Leder du efter datasæt?")

**Comment by amatzen** [comment]
`mauran/DB-Danmark` ?

**Comment by mauran** [comment]
@amatzen DB-Danmark? Why not Data-Danmark?

**Comment by NoahBohme** [comment]
Data-Danmark er bedre

**Comment by boserup** [comment]
Hvad med `mauran/open-data-danmark`?

**Comment by mauran** [comment]
@boserup Jeg kan bedre lide dit navn. Mest beskrivende. Jeg har oprettet repository og migrerer links med datasæt dertil når tiden lige er der 👍🏾

**Comment by mauran** [comment]
https://github.com/mauran/open-data-denmark
