### ISSUE TITLE
Ordregister.dk

### ISSUE THREAD

**Issue by hypesystem** [mauran/API-Danmark#123]
Heyo @mauran - jeg ved ikke lige i hvilken kategori denne passer, så nu smider jeg den her :smile: idet datasættet også kan downloades kan det også være en kandidat til https://github.com/mauran/open-data-denmark

https://ordregister.dk/ indeholder alle officielle danske ord, og er basis for bl.a. ordbøger. Det er ikke et vildt godt API, men man kan dog slå data op via en URL. Alternativt kan man downloade de lidt under 600.000 rækker med ord i datasættet COR.

**Comment by boserup** [comment]
@hypesystem Du må gerne lave en PR på [mauran/open-data-denmark](https://github.com/mauran/open-data-denmark) :)

**Comment by mauran** [comment]
Så det tilføjet til listen - tak for tip @hypesystem!
