### ISSUE TITLE
Forbedringer og mere information 

### ISSUE THREAD

**Issue by mauran** [mauran/API-Danmark#27]
Det kunne være lækkert hvis nogen gad at omskrive hele dokumentet, til at være en tabel indeholdende information som navn(med link), API-type(JSON/XML), om det er login eller frit at bruge. Fx. 

## Betalingsløsninger

| API  |  Type | Gratis at bruge  |
|---|---|---|
|  [Danmarks Adressers Web API - DAWA](http://mauran.me) | JSON  | Ja  |

Hvad tænker i @emilstahl @boserup @LasseRafn @drcd

**Comment by LasseRafn** [comment]
Min mail gik ikke igennem 🤔... anyway, jeg er on it 👍

**Comment by emilstahl** [comment]
God idé!

**Comment by emilstahl** [comment]
Skal kolonnen "Gratis at bruge" ikke hedde noget andet? Det er vel nærmere om det er åbent/public eller private API?

**Comment by LasseRafn** [comment]
God idé ifht. åben/public. I min PR #28 stiller jeg også lidt spørgsmål til "gratis" kolonnen

**Comment by mauran** [comment]
Det sgu smukt 🎉
