### ISSUE TITLE
et eller en issue?

### ISSUE THREAD

**Issue by mauran** [mauran/API-Danmark#30]
`Kender du et dansk API der mangler på listen? Så send et pull request afsted eller opret en issue!` står der i README'en nu.

Hedder det et issue eller en issue? Jeg er usikker nu

**Comment by bdoner** [comment]
[Et issue](https://dsn.dk/?retskriv=issue&ae=0)

**Comment by LasseRafn** [comment]
Bare skriv det 100% dansk :joy: 

> Så send en træk anmodning eller opret et problem

**Comment by mauran** [comment]
Pfft. Det blev et issue
