### ISSUE TITLE
Rapport om offentlige åbne data

### ISSUE THREAD

**Issue by mikini** [mauran/API-Danmark#34]
Rigsrevisionen udgav i går en rapport om åbne offentlige data. De identificerede 921 åbne datasæt, afhængigt af scopet for denne liste kunne nogle måske være relevante? Se http://www.rigsrevisionen.dk/publikationer/2019/122018/.

**Comment by mauran** [comment]
Tjekkede dokumentet igennem og kunne ikke se noget API som vi ikke allerede havde skrevet ned på listen. 😄  - Så vi er up 2 date
