### ISSUE TITLE
Cirkle K

### ISSUE THREAD

**Issue by mauran** [mauran/API-Danmark#46]
Man kan vel argumentere for om et endpoint der bliver opdateret med data er et "API"
https://www.circlek.dk/priser

**Comment by tanghus** [comment]
Nu følger jeg kun med på sidelinjen, men det er jo ikke et link man kan parse, med mindre man HTML scraper.

**Comment by mauran** [comment]
![image](https://user-images.githubusercontent.com/282398/103106550-c9a2cc80-4636-11eb-9f89-6d944a03075e.png)

Klik på historiske priser og du får en CSV som du kan parse, inklusiv dagens pris 😀

**Comment by tanghus** [comment]
Ah, den fangede jeg ikke.

**Comment by mauran** [comment]
@LasseRafn Hvad tænker du?

**Comment by LasseRafn** [comment]
@mauran kan se en service eller app bruge dataen som den er, så synes godt det kan inkluderes 😄!

**Comment by mauran** [comment]
Tilføjet!
