### ISSUE TITLE
Tilføj CHR

### ISSUE THREAD

**Issue by blaavand** [mauran/API-Danmark#51]
Det centrale husdyr register mangler på din liste: https://chr.fvst.dk.

Det er et offentligt tilgængeligt api, som er gratis at bruge, man skal dog oprettes som bruger, men det er også gratis.

**Comment by mauran** [comment]
Tak @blaavand. Så det tilføjet 😄

**Comment by ollive-r** [comment]
Hej [blaavand](https://github.com/blaavand)
Hvor finder du CHRs API på deres hjemmeside, døjer med at finde den. Håber du kan hjælpe. bh.

**Comment by hypesystem** [comment]
Se "Webservice til CHR" under Genveje i højre side :smilE:
