### ISSUE TITLE
Rejseplanen backend API

### ISSUE THREAD

**Issue by eisbaw** [mauran/API-Danmark#68]
Hej, rejseplanen er ikke dansk udviklet men lavet af HACON. 
Systemet hedder HAFAS. https://second.wiki/wiki/hafas
rejseplanen hedder internt RKRP.

RKRP er portet til https://github.com/FahrplanDatenGarten/pyhafas

HAFAS bruges overalt i Europa til offentlig transport.

**Comment by mauran** [comment]
Hej @eisbaw! 

Tak for informationen. Det var virkelig interessant læsning 😄 - Giver rigtig god mening at der brugs HAFAS. Jeg synes dog stadig at Rejseplanen fortjener sin plads på API-Danmark da det trods alt stadig er "dansk" data der kan konsumeres. 👍🏾  

Jeg lukker dette issue.

**Comment by eisbaw** [comment]
@mauran Helt enig, at Rejseplanen Labs skal forblive i listen.
Min tanke var dog at tilføje et entry _mere_: Rejseplanen-via-HAFAS.
