### ISSUE TITLE
GraphQL api'er bliver listet som JSON

### ISSUE THREAD

**Issue by Admiral-Enigma** [mauran/API-Danmark#77]
Er det ikke lidt misvisende at fx Dandomain webshop/smartweb bliver listet som værende JSON/SOAP når der reelt set kun er en GraphQL og SOAP api?

**Comment by mauran** [comment]
Jo. Vil du opdatere?

**Comment by mauran** [comment]
Noah kom dig i forkøbet kan jeg se 🔥
