### ISSUE TITLE
Uddateret DanDomain API type 

### ISSUE THREAD

**Issue by eriksen360** [mauran/API-Danmark#89]
Det fremgår af Hosting -> DanDomain Webshop API at typen er af GraphQL/SOAP. v1 er REST/SOAP og er deprecated, mens v2 er REST. Selvom både v1, og v2 er tilgængelige bør typen vel opdateres til at matche v2 spec?

Link: https://support.dandomain.dk/webshop-hjaelp/api/api-documentation/

**Comment by mauran** [comment]
Good point! Laver du en PR? 😄

**Comment by mauran** [comment]
#90
