### ISSUE TITLE
Bør vi liste API'er der ikke længere er tilgængelige?

### ISSUE THREAD

**Issue by mauran** [mauran/API-Danmark#94]
Som det er lige nu overstreger vi API'er på listen som ikke længere er tilgængelige, fordi det har vi altid gjort. Men giver det overhovedet mening at gøre det? Hvad tænker i?

**Comment by mauran** [comment]
Vil rigtig gerne høre jeres holdning @LasseRafn @NoahBohme @amatzen @tanddant @boserup

**Comment by NoahBohme** [comment]
Overstregning af API'er på listen, som ikke længere er tilgængelige, giver brugerne en mulighed for at se tidligere API'er og muligvis identificere nye API'er, som kan have erstattet de nedlagte API'er. Det kan også hjælpe med at backtracke, hvornår API'er blev utilgængelige, og hvad der kan have ført til deres nedlæggelse.

Ved at have en opdateret liste over tilgængelige API'er og en oversigt over tidligere API'er, der er blevet nedlagt, kan vi give brugerne en bedre forståelse af API-landskabet i Danmark og hjælpe dem med at finde og bruge de relevante API'er i deres projekter - derfor mener jeg det skal bevares.

**Comment by LasseRafn** [comment]
Mit instinkt ville være at slette, for at rydde op og holde listen overskuelig.

Jeg kan dog også se @NoahBohme's argument for at beholde dem. Jeg er 50/50.

Måske flytte dem til bunden eller noget, for at 'rydde op'?

**Comment by Tanddant** [comment]
Jeg hælder til en "deprecated" liste, på den måde findes det historiske overblik, også uden at man skal kigge tilbage i commits, og man kan CTRL+F søge i den aktuelle udgave uden at blive forvirret over døde APIer

**Comment by mauran** [comment]
En deprecated liste lyder ganske fornuftigt. Nogen der tager teten?

**Comment by mauran** [comment]
Done 🎉
